version: "3.8"
services:
  rabbitmq:
    hostname: rabbitmq  
    image: myrabbit
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host rabbitmq
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
          condition: any
          delay: 5s
          window: 120s
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 5671
        published: 5671
        protocol: tcp
        mode: host
      - target: 5552
        published: 5552
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    networks:
      - supersuperstreams
  consumer:
    image: consumer
    depends_on:
      - rabbitmq
    deploy:
      replicas: 6
      restart_policy:
          condition: any
          delay: 5s
          window: 120s
    networks:
      - supersuperstreams
  producer:
    image: producer
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
          condition: any
          delay: 5s
          window: 120s
    networks:
      - supersuperstreams
networks:
  supersuperstreams:
      name: supersuperstreams